#Counstant
import os

COUNST_MODULE_NAME='robincounst'
COUNST_MODULE_DIR=os.getcwd()
COUNST_RO_INT_SIZE_32=2**32
COUNST_RO_INT_SIZE_64=2**64
COUNST_RO_LENGTH_INT_32=len(str(COUNST_RO_INT_SIZE_32))
COUNST_RO_LENGTH_INT_64=len(str(COUNST_RO_INT_SIZE_64))
COUNST_RO_CHAR_SIZE=2**16
COUNST_ROBIN_VERSION='1.0.0'
